version: "3.1"

networks:
  audicus:

services:
  app:
    container_name: APP
    build:
      context: .
      dockerfile: ./compose/app/Dockerfile
    env_file:
      - ./.env
    volumes:
      - ${PWD}:/app
    networks:
      - audicus
    command: "supervisord"
    ports:
      - "6000:6000"
