version: "3.1"

networks:
  urlnet:

services:
  app:
    container_name: APP
    build:
      context: .
      dockerfile: ./compose/app/Dockerfile
    env_file:
      - ./.env
    volumes:
      - ${PWD}:/app
    networks:
      - urlnet
    command: "supervisord"
