# This workflow will install Python dependencies, run tests and lint.
# For more information see: https://docs.github.com/en/actions/use-cases-and-examples/building-and-testing/building-and-testing-python
name: Python Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x" # Specify your desired Python version
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # If you use a requirements.txt file:
          pip install -r requirements/dev.txt
      - name: Run pytest
        run: pytest
